[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "croco"
version = "0.0.1"
dynamic = ["dependencies"]

[tool.setuptools.packages.find]
where = ["."]
include = ["models"]
namespaces = false
